### ISSUE TITLE
Kotlin Language Client Crash

### ISSUE THREAD

**Issue by CmdrNorthpaw** [fwcd/vscode-kotlin#44] opened 2020-07-08 09:24 UTC
**Describe the bug**
When starting the editor, the extension does not start and throws the following error:
```[2020-07-08 10:12:01.031] [exthost] [error] Activating extension fwcd.kotlin failed due to an error:
[2020-07-08 10:12:01.035] [exthost] [error] Error: Internal error.
	at /home/sam/.vscode/extensions/fwcd.kotlin-0.2.18/dist/extension.js:1:39853
	at /home/sam/.vscode/extensions/fwcd.kotlin-0.2.18/dist/extension.js:1:40147
	at Immediate.<anonymous> (/home/sam/.vscode/extensions/fwcd.kotlin-0.2.18/dist/extension.js:1:40506)
	at processImmediate (internal/timers.js:439:21)
```
It also gets stuck in an infinite loop of "initializing the Kotlin Language Server"
**To Reproduce**
1. Install the extension
2. See error

**Expected behavior**
For the Kotlin Language Client to not crash

**Extension version**
Which version of the VSCode extension you are running.
0.2.18
**Additional context**
I'm running VSCode 1.46 on Arch Linux. 
/

**Comment by fwcd** [comment] 2020-07-08 11:14
Could you check if there are any further errors/stack traces in the output tab or VSCode dev tools?

**Comment by CmdrNorthpaw** [comment] 2020-07-08 13:00
I'd like to help but I grabbed that from the Extension Host logs and I don't know how to go deeper into it.

**Comment by fwcd** [comment] 2020-07-08 13:34
Kotlin has a separate output log that can be accessed from the same dropdown as the Extension Host.

**Comment by CmdrNorthpaw** [comment] 2020-07-08 13:56
Really? If I press Shift+Ctrl+P and select Developer: Show Logs, the only options I get are Preferences Sync, Window, Main, Shared and Extension Host.

**Comment by fwcd** [comment] 2020-07-08 13:59
Click on the 'Output' tab on the bottom panel

**Comment by CmdrNorthpaw** [comment] 2020-07-08 14:08
Oh, I see, thank you. Here's the full log: 
```[Info  - 13:08:51] main      Adding script definitions [ScriptTemplateWithArgs]
[Info  - 13:08:51] main      Connected to client
[Info  - 13:08:51] client    Adding workspace file:///home/sam/Documents/Code/Kotlin%20Plugin to source path
Jul 08, 2020 1:08:51 PM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
SEVERE: Internal error: java.lang.reflect.InvocationTargetException
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:192)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 11 more
Caused by: java.lang.IllegalArgumentException: Illegal character in path at index 38: file:///home/sam/Documents/Code/Kotlin Plugin
	at java.base/java.net.URI.create(URI.java:883)
	at org.javacs.kt.util.URIsKt.parseURI(URIs.kt:14)
	at org.javacs.kt.KotlinLanguageServer.initialize(KotlinLanguageServer.kt:73)
	... 16 more
Caused by: java.net.URISyntaxException: Illegal character in path at index 38: file:///home/sam/Documents/Code/Kotlin Plugin
	at java.base/java.net.URI$Parser.fail(URI.java:2913)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3084)
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3166)
	at java.base/java.net.URI$Parser.parse(URI.java:3114)
	at java.base/java.net.URI.<init>(URI.java:600)
	at java.base/java.net.URI.create(URI.java:881)
	... 18 more

[Error - 13:08:51] client    Internal error: java.lang.reflect.InvocationTargetException
[Error - 13:08:51] java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[Error - 13:08:51] 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
[Error - 13:08:51] 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
[Error - 13:08:51] 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
[Error - 13:08:51] 	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
[Error - 13:08:51] 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:192)
[Error - 13:08:51] 	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
[Error - 13:08:51] 	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
[Error - 13:08:51] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[Error - 13:08:51] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[Error - 13:08:51] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[Error - 13:08:51] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[Error - 13:08:51] 	at java.base/java.lang.Thread.run(Thread.java:834)
[Error - 13:08:51] Caused by: java.lang.reflect.InvocationTargetException
[Error - 13:08:51] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[Error - 13:08:51] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[Error - 13:08:51] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[Error - 13:08:51] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[Error - 13:08:51] 	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
[Error - 13:08:51] 	... 11 more
[Error - 13:08:51] Caused by: java.lang.IllegalArgumentException: Illegal character in path at index 38: file:///home/sam/Documents/Code/Kotlin Plugin
[Error - 13:08:51] 	at java.base/java.net.URI.create(URI.java:883)
[Error - 13:08:51] 	at org.javacs.kt.util.URIsKt.parseURI(URIs.kt:14)
[Error - 13:08:51] 	at org.javacs.kt.KotlinLanguageServer.initialize(KotlinLanguageServer.kt:73)
[Error - 13:08:51] 	... 16 more
[Error - 13:08:51] Caused by: java.net.URISyntaxException: Illegal character in path at index 38: file:///home/sam/Documents/Code/Kotlin Plugin
[Error - 13:08:51] 	at java.base/java.net.URI$Parser.fail(URI.java:2913)
[Error - 13:08:51] 	at java.base/java.net.URI$Parser.checkChars(URI.java:3084)
[Error - 13:08:51] 	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3166)
[Error - 13:08:51] 	at java.base/java.net.URI$Parser.parse(URI.java:3114)
[Error - 13:08:51] 	at java.base/java.net.URI.<init>(URI.java:600)
[Error - 13:08:51] 	at java.base/java.net.URI.create(URI.java:881)
[Error - 13:08:51] 	... 18 more
[Error - 13:08:51] Server initialization failed.
  Message: Internal error.
  Code: -32603 
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:192)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 11 more
Caused by: java.lang.IllegalArgumentException: Illegal character in path at index 38: file:///home/sam/Documents/Code/Kotlin Plugin
	at java.base/java.net.URI.create(URI.java:883)
	at org.javacs.kt.util.URIsKt.parseURI(URIs.kt:14)
	at org.javacs.kt.KotlinLanguageServer.initialize(KotlinLanguageServer.kt:73)
	... 16 more
Caused by: java.net.URISyntaxException: Illegal character in path at index 38: file:///home/sam/Documents/Code/Kotlin Plugin
	at java.base/java.net.URI$Parser.fail(URI.java:2913)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3084)
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3166)
	at java.base/java.net.URI$Parser.parse(URI.java:3114)
	at java.base/java.net.URI.<init>(URI.java:600)
	at java.base/java.net.URI.create(URI.java:881)
	... 18 more

[Error - 13:08:51] Starting client failed
  Message: Internal error.
  Code: -32603 
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:120)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:261)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:190)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:192)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 11 more
Caused by: java.lang.IllegalArgumentException: Illegal character in path at index 38: file:///home/sam/Documents/Code/Kotlin Plugin
	at java.base/java.net.URI.create(URI.java:883)
	at org.javacs.kt.util.URIsKt.parseURI(URIs.kt:14)
	at org.javacs.kt.KotlinLanguageServer.initialize(KotlinLanguageServer.kt:73)
	... 16 more
Caused by: java.net.URISyntaxException: Illegal character in path at index 38: file:///home/sam/Documents/Code/Kotlin Plugin
	at java.base/java.net.URI$Parser.fail(URI.java:2913)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3084)
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3166)
	at java.base/java.net.URI$Parser.parse(URI.java:3114)
	at java.base/java.net.URI.<init>(URI.java:600)
	at java.base/java.net.URI.create(URI.java:881)
	... 18 more

[Info  - 13:08:51] client    Awaiting async termination...
[Info  - 13:08:51] client    Awaiting debouncer termination...
```

**Comment by fwcd** [comment] 2020-07-08 14:44
This is a duplicate of https://github.com/fwcd/kotlin-language-server/issues/200, was fixed in https://github.com/fwcd/kotlin-language-server/pull/204. The fix hasn't been deployed to a release yet, however.

For now, you could either remove the space in your folder name, wait for the next KLS release or build KLS yourself.

Thanks :)

**Closed by fwcd** 2020-07-08 14:44 UTC
Labels: bug
