### ISSUE TITLE
Infinite Unpacking 

### ISSUE THREAD

**Issue by joacatito** [fwcd/vscode-kotlin#36] opened 2020-06-04 21:05 UTC
I've installed Kotlin and tried to use it.

In the last 30 minutes (as I installed), for two times (15 minutes each) I've stucked on two messages in VS Code status bar:

- Unpaking Kotlin Language Server 0.6.0...
- Unpaking Kotlin Debug Adapter 0.2.6...

![image](https://user-images.githubusercontent.com/16540138/83809841-83cbea00-a68d-11ea-826d-23c25ff67a21.png)

The extension is not activate and I cannot start my Project.

**Comment by fwcd** [comment] 2020-06-04 23:11
That's unfortunate, I'll investigate this issue...

**Comment by fwcd** [comment] 2020-06-04 23:16
The issue was caused by a breaking API change in the `extract-zip` module and should be fixed in the next patch.

**Closed** 2020-06-04 23:21 UTC
Labels: bug
