### ISSUE TITLE
Kotlin intellisense

### ISSUE THREAD

**Issue by cruzortiz99** [fwcd/vscode-kotlin#60] opened 2021-02-02 10:13 UTC
### Motivation
As java intellisense, it would be a perfect feature to improve kotlin programing on VScode
### Description
Intellisense like there is in java extension pack. So it could autocomplete the code importing the package selected

**Comment by fwcd** [comment] 2021-02-02 13:09
Duplicate of fwcd/kotlin-language-server#10.

**Closed by fwcd** 2021-02-02 13:09 UTC
Labels: enhancement
